### ISSUE TITLE
StackOverflowError onMeasureChild

### ISSUE THREAD

**Issue by arjunkn** [henrytao-me/smooth-app-bar-layout#148]
I got this error on implementing smooth smoothappbarlayout

`Process: com.solutions.miyamiya, PID: 22565
                                                                        java.lang.StackOverflowError: stack size 8MB
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
                                                                            at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:755)
                                                                            at me.hen`

**Comment by henrytao-me** [comment]
Hi @arjunkn 

What version of AppCompat, SupportDesign and SmoothAppBarLayout are you using?

**Comment by arjunkn** [comment]
```
compile 'me.henrytao:smooth-app-bar-layout:23.2.1'
compile 'com.android.support:design:24.2.1'
```

**Comment by henrytao-me** [comment]
Can you try these?

```
compile 'me.henrytao:smooth-app-bar-layout:24.2.1.0'
compile 'com.android.support:design:24.2.1'
```

**Comment by henrytao-me** [comment]
I believe it will work. So, I will close this issue for now. Feel free to ping me if you still have this issue. Thanks

**Comment by arjunkn** [comment]
thanks it worked.. sorry for the late replay.
