### ISSUE TITLE
Error inflating class android.support.design.widget.CollapsingToolbarLayout

### ISSUE THREAD

**Issue by arjunkn** [henrytao-me/smooth-app-bar-layout#156]
When i use 

compile 'me.henrytao:smooth-app-bar-layout:23.2.1'

i am getting Error inflating class android.support.design.widget.CollapsingToolbarLayout full error log  is given.

I need to use the version 23.2 or greater must me less than 24

`FATAL EXCEPTION: main
                                                                        Process: com.solutions.miyamiya, PID: 25251
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.solutions.miyamiya/com.solutions.miyamiya.CustomerMainHomeActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #21: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                         Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #21: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                            at com.solutions.miyamiya.CustomerMainHomeActivity.onCreate(CustomerMainHomeActivity.java:271)
                                                                            at android.app.Activity.performCreate(Activity.java:6259)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                         Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                            at com.solutions.miyamiya.CustomerMainHomeActivity.onCreate(CustomerMainHomeActivity.java:271) 
                                                                            at android.app.Activity.performCreate(Activity.java:6259) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                            at com.solutions.miyamiya.CustomerMainHomeActivity.onCreate(CustomerMainHomeActivity.java:271) 
                                                                            at android.app.Activity.performCreate(Activity.java:6259) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                         Caused by: java.lang.NoSuchMethodError: No static method setLayoutDirection(Landroid/graphics/drawable/Drawable;I)V in class Landroid/support/v4/graphics/drawable/DrawableCompat; or its super classes (declaration of 'android.support.v4.graphics.drawable.DrawableCompat' appears in /data/data/com.solutions.miyamiya/files/instant-run/dex/slice-com.android.support-support-v4-24.0.0_05b83b34cfdb161d0c89dee2239abb07d3621625-classes.dex)
                                                                            at android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)
                                                                            at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)
                                                                            at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                            at com.solutions.miyamiya.CustomerMainHomeActivity.onCreate(CustomerMainHomeActivity.java:271) 
                                                                            at android.app.Activity.performCreate(Activity.java:6259) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) `

**Comment by henrytao-me** [comment]
Hi @arjunkn 

Did you solve the issue?

**Comment by arjunkn** [comment]
yes.. that was problem with version. I used 

`compile ('com.android.support:support-v4:23.2.1'){
        force=true;
    }`
to solve it.

**Comment by KhinSandar** [comment]
Dear arjunkn , It works for me. Thanks much.

**Comment by yavuzyoldas** [comment]
implementation 'com.android.support:design:29.1.1'

<com.google.android.material.appbar.AppBarLayout
  android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="78dp"
>
</com.google.android.material.appbar.AppBarLayout>
