### ISSUE TITLE
error inflating class android.support.design.widget.collapsingtoolbarlayout 

### ISSUE THREAD

**Issue by Y-JH** [henrytao-me/smooth-app-bar-layout#212]
FATAL EXCEPTION: main
                                                               Process: com.jiujia.cn, PID: 13632
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jiujia.cn/com.jiujia.cn.postReward.activity.OrderInfoAty}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:160)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6248)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
                                                                Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                   at com.jiujia.cn.postReward.activity.OrderInfoAty.onCreate(OrderInfoAty.java:52)
                                                                   at android.app.Activity.performCreate(Activity.java:6754)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                   at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(Unknown Source)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:160)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6248)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
                                                                Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 8: TypedValue{t=0x2/d=0x7f01016d a=-1}
                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:927)
                                                                   at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:214)
                                                                   at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:143)
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:883) 
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:886) 
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:522) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:430) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                   at com.jiujia.cn.postReward.activity.OrderInfoAty.onCreate(OrderInfoAty.java:52) 
                                                                   at android.app.Activity.performCreate(Activity.java:6754) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                   at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:160) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6248) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

**Comment by Y-JH** [comment]
android = [
      compileSdkVersion: 25,
      buildToolsVersion: "25.0.0",
      minSdkVersion    : 19,
      targetSdkVersion : 25,
  ]

**Comment by Vijeet3106** [comment]
[google](www.google.com)
